# SPDX-License-Identifier: MIT
"""
missclimatepy.features
======================

Date-handling and feature-engineering utilities used across MissClimatePy.

All models in the package are intentionally restricted to purely
spatio–temporal predictors:

    [latitude, longitude, altitude, year, month, day, doy, (doy_sin, doy_cos)]

This module provides small, well-tested helpers to ensure consistent
construction of these features.
"""

from __future__ import annotations

from typing import Iterable, List, Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Datetime helpers
# ---------------------------------------------------------------------------


def ensure_datetime_naive(series: pd.Series) -> pd.Series:
    """
    Ensure a pandas Series is converted to timezone-naive ``datetime64[ns]``.

    Parameters
    ----------
    series : pandas.Series
        Input series containing timestamps or strings.

    Returns
    -------
    pandas.Series
        Series with dtype ``datetime64[ns]`` and no timezone information.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("`ensure_datetime_naive` expects a pandas.Series.")

    dt = pd.to_datetime(series, errors="coerce")

    # Drop timezone information if present
    if hasattr(dt.dt, "tz_localize"):
        try:
            dt = dt.dt.tz_localize(None)
        except TypeError:
            # Already tz-naive – nothing to do
            pass
    return dt


# ---------------------------------------------------------------------------
# Calendar feature engineering
# ---------------------------------------------------------------------------


def add_calendar_features(
    df: pd.DataFrame,
    date_col: str,
    *,
    add_cyclic: bool = False,
) -> pd.DataFrame:
    """
    Add calendar-based features derived from a date column.

    The following columns are created:

    - ``"year"``  : calendar year
    - ``"month"`` : calendar month (1–12)
    - ``"day"``   : day of month (1–31)
    - ``"doy"``   : day of year (1–366)

    If ``add_cyclic=True``, two additional harmonic features are added:

    - ``"doy_sin"``
    - ``"doy_cos"``

    Parameters
    ----------
    df : pandas.DataFrame
        Input DataFrame. It is **not** modified in-place; a copy is returned.
    date_col : str
        Name of the column containing dates or date-like objects.
    add_cyclic : bool, default False
        Whether to add sine and cosine of the day-of-year.

    Returns
    -------
    pandas.DataFrame
        A copy of the input with the additional calendar feature columns.
    """
    if date_col not in df.columns:
        raise KeyError(f"`date_col='{date_col}'` not found in DataFrame columns.")

    out = df.copy()
    out[date_col] = ensure_datetime_naive(out[date_col])

    # Basic calendar components
    out["year"] = out[date_col].dt.year.astype("Int64")
    out["month"] = out[date_col].dt.month.astype("Int64")
    out["day"] = out[date_col].dt.day.astype("Int64")
    out["doy"] = out[date_col].dt.dayofyear.astype("Int64")

    if add_cyclic:
        # Use float dtype for harmonic terms
        doy_float = out["doy"].astype(float)
        radians = 2.0 * np.pi * (doy_float - 1.0) / 365.0
        out["doy_sin"] = np.sin(radians)
        out["doy_cos"] = np.cos(radians)

    return out


def default_feature_names(
    *,
    lat_col: str,
    lon_col: str,
    alt_col: str,
    add_cyclic: bool = False,
) -> List[str]:
    """
    Return the default list of predictor column names used by the models.

    IMPORTANT:
    Tests for MissClimatePy expect the classic minimal feature set:

        [lat, lon, alt, year, month, doy]

    If cyclic features are enabled, append ["doy_sin", "doy_cos"].

    Note that although the DataFrame generated by `add_calendar_features`
    contains a "day" column, it is *not* part of the default feature list.
    """
    feats: List[str] = [
        lat_col,
        lon_col,
        alt_col,
        "year",
        "month",
        "doy",
    ]

    if add_cyclic:
        feats.extend(["doy_sin", "doy_cos"])

    return feats


# ---------------------------------------------------------------------------
# Column validation
# ---------------------------------------------------------------------------


def validate_required_columns(
    df: pd.DataFrame,
    required: Iterable[str],
    *,
    context: Optional[str] = None,
) -> None:
    """
    Validate that all required columns are present in a DataFrame.

    Parameters
    ----------
    df : pandas.DataFrame
        DataFrame to be validated.
    required : iterable of str
        Column names that must be present.
    context : str, optional
        Optional label to include in the error message (e.g. the caller
        function name). This parameter exists mainly to make error messages
        used in tests and public APIs more informative.

    Raises
    ------
    KeyError
        If any of the required columns are missing.
    """
    missing = [col for col in required if col not in df.columns]
    if missing:
        ctx = f" in {context}" if context else ""
        raise KeyError(f"Missing required columns{ctx}: {missing!r}")


__all__ = [
    "ensure_datetime_naive",
    "add_calendar_features",
    "default_feature_names",
    "validate_required_columns",
]
